# Generated by Django 5.1.5 on 2025-01-25 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0003_alter_ticket_escalation_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_performed', models.TextField()),
                ('parts_used', models.TextField(blank=True, null=True)),
                ('technician_signature', models.CharField(max_length=255)),
                ('customer_signature', models.CharField(max_length=255)),
                ('on_site_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('stop_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='tickets.ticket')),
            ],
        ),
    ]
