# Generated by Django 5.1.5 on 2025-02-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_category', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for primary departments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tickets.department')),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low — Minor or no immediate impact'), ('Medium', 'Medium — Manageable disruption'), ('High', 'High — Significant urgency'), ('Critical', 'Critical — Immediate attention required')], default='Low', help_text='Set the urgency level for the ticket.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_department', models.ForeignKey(blank=True, help_text='Select the primary department category.', limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_tickets', to='tickets.department')),
                ('sub_department', models.ForeignKey(blank=True, help_text='Select the sub-department (child of the primary department).', limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tickets', to='tickets.department')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('it_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.itticket')),
            ],
        ),
    ]
