# Generated by Django 5.1.5 on 2025-01-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('store_address', models.TextField()),
                ('work_requested', models.TextField()),
                ('store_contact_name', models.CharField(max_length=100)),
                ('store_contact_phone', models.CharField(max_length=15)),
                ('work_performed', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
