# Generated by Django 5.1.5 on 2025-01-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_unique_id_alter_ticket_escalation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='escalation_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], null=True),
        ),
    ]
