# Generated by Django 5.1.5 on 2025-01-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email address of the user creating the ticket.', max_length=254)),
                ('subject', models.CharField(help_text='A short summary of the issue or request.', max_length=255)),
                ('description', models.TextField(help_text='A detailed description of the issue or request.')),
                ('token', models.CharField(help_text='A unique JWT token for tracking the ticket.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the ticket was created.')),
            ],
        ),
    ]
